[package]
name = "cspuz_core_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "cspuz_core_python"
crate-type = ["cdylib"]

[dependencies]
cspuz_core = { path = "../cspuz_core", features = ["parser", "cli"] }
pyo3 = { version = "0.23.4", features = ["extension-module"] }
